from etl_ap import etl_ap #Librería desarrollada por Elico
from datetime import datetime
import pytz
import json
import requests
from time import sleep
import snap7
import struct
import csv
from snap7.exceptions import Snap7Exception
from requests.exceptions import RequestException

variables = [
"RUN_BOMBA_EBALL_S1",
"RUN_BOMBA_EBALL_S2",
"RUN_BOMBA_EBALL_S3",
"START_BOMBA_POZO_1",
"STOP_BOMBA_POZO_1",
"RUN_BOMBA_POZO_1",
"FAULT_BOMBA_POZO_1",
"START_BOMBA_POZO_2",
"STOP_BOMBA_POZO_2",
"FAULT_BOMBA_POZO_2",
"START_BOMBA_POZO_3",
"STOP_BOMBA_POZO_3",
"FAULT_BOMBA_POZO_3",
"BOMBA_EBALL_1",
"BOMBA_EBALL_2",
"BOMBA_EBALL_3",
"BOMBA_FILTRACION_1",
"BOMBA_FILTRACION_2",
"BOMBA_FILTRACION_3",
"BOMBA_SUMINISTRO_1",
"BOMBA_SUMINISTRO_2",
"MEDIDOR_CAUDAL_POZO_1",
"MEDIDOR_PRESIÓN_POZO_1",
"MEDIDOR_NIVEL_POZO_1",
"MEDIDOR_CAUDAL_POZO_2",
"MEDIDOR_PRESIÓN_POZO_2",
"MEDIDOR_NIVEL_POZO_2",
"MEDIDOR_PRESIÓN_SUMINISTRO (PT02_Distribucion)",
"MEDIDOR_CAUDAL_POZO_3",
"MEDIDOR_PRESIÓN_POZO_3",
"MEDIDOR_NIVEL_POZO_3",
"TRANSDUCTOR_PRESION_FILTRO_001_FASE_1",
"TRANSDUCTOR_PRESION_FILTRO_002_FASE_1",
"TRANSDUCTOR_PRESION_FILTRO_003_FASE_1",
"TRANSDUCTOR_PRESION_FILTRO_004_FASE_1",
"TRANSDUCTOR_PRESION_FILTRO_001_FASE_2",
"TRANSDUCTOR_PRESION_FILTRO_002_FASE_2",
"TRANSDUCTOR_PRESION_FILTRO_003_FASE_2",
"TRANSDUCTOR_PRESION_FILTRO_004_FASE_2",
"MEDIDOR_CAUDAL_FILTRACION_1",
"MEDIDOR_CAUDAL_FILTRACION_2",
"MEDIDOR_CAUDAL_DISTRIBUCION (FT_DISTRIBUCION)",
"MEDIDOR_NIVEL_ALMACENAMIENTO_1",
"MEDIDOR_NIVEL_ALMACENAMIENTO_2",
"MEDIDOR_NIVELES_FOSO",
"MEDIDOR_CAUDAL_EBALL",
"MEDIDOR_PRESIÓN_EBALL",
]

etl_ALP = etl_ap.etl_ap(
    ip='192.168.0.1', 
    rack=0, slot=1, name='plc_1', 
    route_log='/home/elicoubuntu/Documents/etl2.log', 
    url_api="",
    token='',
    variables=variables,
    db=1,
)

etl_ALP.run()